using AdventOfCode2025.Puzzles;

namespace UnitTests;

public class Day7Tests
{
    private readonly IPuzzle _solver = new Day7();

    [Fact]
    public void Part1ExampleCase()
    {
        // Arrange
        var input = """
                    .......S.......
                    ...............
                    .......^.......
                    ...............
                    ......^.^......
                    ...............
                    .....^.^.^.....
                    ...............
                    ....^.^...^....
                    ...............
                    ...^.^...^.^...
                    ...............
                    ..^...^.....^..
                    ...............
                    .^.^.^.^.^...^.
                    ...............
                    """;

        // Act
        var result = _solver.Solve(input);

        // Assert
        var part1 = result[0];
        Assert.Equal("21", part1);
    }

    [Theory]
    [InlineData("""
                ...S...
                .......
                ...^...
                .......
                """, "1")]
    [InlineData("""
                ...S...
                .......
                ...^...
                .......
                ..^.^..
                .......
                """, "3")]
    [InlineData("""
                ...S...
                .......
                ...^...
                .......
                ..^.^..
                .......
                ..^..^.
                .......
                """, "4")]
    [InlineData("""
                ...S...
                .......
                ...^...
                .......
                ..^.^..
                .......
                ..^..^.
                .......
                .^.....
                .......
                """, "5")]
    public void Part1Cases(string input, string expectedResult)
    {
        // Act
        var result = _solver.Solve(input);

        // Assert
        var part1 = result[0];
        Assert.Equal(expectedResult, part1);
    }

    [Fact]
    public void Part2ExampleCase()
    {
        // Arrange
        var input = """
                    .......S.......
                    ...............
                    .......^.......
                    ...............
                    ......^.^......
                    ...............
                    .....^.^.^.....
                    ...............
                    ....^.^...^....
                    ...............
                    ...^.^...^.^...
                    ...............
                    ..^...^.....^..
                    ...............
                    .^.^.^.^.^...^.
                    ...............
                    """;

        // Act
        var result = _solver.Solve(input);

        // Assert
        var part2 = result[1];
        Assert.Equal("40", part2);
    }

    [Theory]
    [InlineData("""
                ...S...
                .......
                ...^...
                .......
                """, "2")]
    [InlineData("""
                ...S...
                .......
                ...^...
                .......
                ..^.^..
                .......
                """, "4")]
    [InlineData("""
                ...S...
                .......
                ...^...
                .......
                ..^.^..
                .......
                ..^..^.
                .......
                """, "5")]
    [InlineData("""
                ...S...
                .......
                ...^...
                .......
                ..^.^..
                .......
                ..^..^.
                .......
                .^.....
                .......
                """, "6")]
    public void Part2Cases(string input, string expectedResult)
    {
        // Act
        var result = _solver.Solve(input);

        // Assert
        var part2 = result[1];
        Assert.Equal(expectedResult, part2);
    }
}